services:
  postgres:
    image: postgres:15
    container_name: zagroscms_postgres
    environment:
      POSTGRES_USER: zagroscms
      POSTGRES_PASSWORD: zagroscms
      POSTGRES_DB: zagroscms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: zagroscms_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: